### ISSUE TITLE
Editor font size doesn't change in Android Studio

### ISSUE THREAD

**Issue by konradg** [mskonovalov/intellij-hidpi-profiles#10]
Steps to reproduce:
- Enable plugin in Android Studio (latest plugin, AS v3.0.1)
- Set the editor font and UI font to X (e.g. 12pt), apply
- Add an HIDPI profile
- Set the editor font and UI font to Y (e.g. 17pt), apply
- Add a second HIDPI profile
- Switch between profiles.

Result: UI font changes while the editor font stays the same size.
The above steps work correctly in other IntelliJ flavors like PyCharm Community Edition.

Any ideas or suggestions? Is it just Android Studio being quirky?

**Comment by saxn-paule** [comment]
Same issue with WebStorm 2017.3.5
UI size changes, editor font stays the same size.

**Comment by mskonovalov** [comment]
fixed in ccbca9047a0c7b1ec0ed6180140c78f4539f3771
