### ISSUE TITLE
Terminal Font

### ISSUE THREAD

**Issue by vastsoun** [mskonovalov/intellij-hidpi-profiles#5]
Hi,

First of all thanks for this plugin. Its great! 

Is there a way to set-it-up to also store the terminal font in the profiles?

**Comment by mskonovalov** [comment]
Thank you for the idea - I think it is very good improvement.
I'll try to find the time to do this.

**Comment by mskonovalov** [comment]
Seems I misunderstood the request - you can change terminal font with Editor -> Colors $ Fonts -> Console Font
It worked all the time but previously (2016.3) you have to close the terminal session and open again.
Now on 2017.1 terminal refreshed automatically.

**Comment by mskonovalov** [comment]
Moreover I decided to add ability to save not only Font size but Font Type itself.
It will be done in next release

**Comment by mskonovalov** [comment]
Oh, sorry, according to this thead
https://intellij-support.jetbrains.com/hc/en-us/community/posts/207004525-terminal-theme
you have to close Terminal window and open again to re-apply font for it.
