### ISSUE TITLE
When starting PHPStorm (at least) the active profile doesn't fully get loaded

### ISSUE THREAD

**Issue by kehh** [mskonovalov/intellij-hidpi-profiles#7]
I have to switch from my current profile (uhd) back to my hd profile (hd) and then back to uhd for all of the profile settings to apply.

### Initial
![initial](https://user-images.githubusercontent.com/12571/33299596-4f0dc2d8-d427-11e7-85c4-d0f047a5616b.png)
### HD
![hd](https://user-images.githubusercontent.com/12571/33299595-4ecfcb90-d427-11e7-8b2e-2be03d4eb0f2.png)
### UHD
![uhd](https://user-images.githubusercontent.com/12571/33299597-4f46b322-d427-11e7-8654-fa43cd5d117c.png)

Is there somewhere I can find where these profiles get stored so I can share them with you?

**Comment by mskonovalov** [comment]
Hi, which version do you use? It seems like compatibility issue with newer version of Idea.
I'll take a look.

**Comment by mskonovalov** [comment]
You mean the problem is that profile is not loaded properly during startup?

**Comment by kehh** [comment]
Yes - incomplete profile load on start up.

**Comment by kehh** [comment]
PHPStorm:
```
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-40-generic
```
hidpi-profiles:
```
Version: 2017.1.1
```

Additionally I'm using the Material Theme UI EAP so am wondering if that is conflicting?

Material Theme UI EAP
```
Version: 1.3.0-171.2953
```

**Comment by mskonovalov** [comment]
Hey @kehh let's check you config file (it is in .../config/options/hidpi.xml)
And did you try to delete all the profiles and create again? Does it help?

**Comment by kehh** [comment]
Here's my config. Going to try deleting it.
```xml
<application>
  <component name="HIDPIProfiles">
    <option name="profiles">
      <list>
        <FontProfile>
          <option name="active" value="true" />
          <option name="consoleFontSize" value="24" />
          <option name="editorFontSize" value="24" />
          <option name="globalFontSize" value="24" />
          <option name="name" value="uhd" />
          <option name="overrideGlobalFont" value="true" />
        </FontProfile>
        <FontProfile>
          <option name="consoleFontSize" value="12" />
          <option name="editorFontSize" value="12" />
          <option name="globalFontSize" value="12" />
          <option name="name" value="hd" />
          <option name="overrideGlobalFont" value="true" />
        </FontProfile>
      </list>
    </option>
  </component>
</application>
```

**Comment by kehh** [comment]
No luck :(
My config file now:
```xml
<application>
  <component name="HIDPIProfiles">
    <option name="profiles">
      <list>
        <FontProfile>
          <option name="consoleFontSize" value="10" />
          <option name="editorFontSize" value="10" />
          <option name="globalFontSize" value="10" />
          <option name="name" value="Default" />
          <option name="overrideGlobalFont" value="true" />
        </FontProfile>
         <FontProfile>
          <option name="active" value="true" />
          <option name="consoleFontSize" value="24" />
          <option name="editorFontSize" value="24" />
          <option name="globalFontSize" value="24" />
          <option name="name" value="uhd" />
          <option name="overrideGlobalFont" value="true" />
        </FontProfile>
      </list>
    </option>
  </component>
</application>
```

**Comment by mskonovalov** [comment]
OK, thank you. Config file looks normal. Will try to test with plugin.

**Comment by kehh** [comment]
Thanks.

**Comment by mskonovalov** [comment]
Seems problem exists, and connected with plugin. Have no idea how to fix yet. Will try.

**Comment by mskonovalov** [comment]
Please re-check in new version

**Comment by kehh** [comment]
@mskonovalov thanks so much. I had to delete my existing profiles and everything's working great now. Thanks for a great plugin.

**Comment by mskonovalov** [comment]
Great! 
You are welcome :)
