### ISSUE TITLE
Font spacing does not change properly

### ISSUE THREAD

**Issue by vastsoun** [mskonovalov/intellij-hidpi-profiles#8]
Hi,

I've been experiencing improper transitioning between profiles. When switching between profiles, I need to restart CLion for the configurations to take effect properly. It looks like the line spacing is not being set correctly. Lastly, after restarting the general IDE fonts are proper but the editor starts out with the last/previous active profile.

This means, every time I start CLion and want to change profiles, I have to do exactly the same steps always:

1. Start CLion.
2. Set the desired profile (which is not the starting one).
3. Restart CLion.
4. Go back to last profile.
5. Finally set the desired profile again.

I have a Thinkpad P50 with a 3840x2160 resolution, running CLion 2017.3 (but also had the same on 2017.2) on Ubuntu 16.04LTS. Also I am using the Material Theme UI plugin.

**Comment by mskonovalov** [comment]
Hi @vastsoun , thank you for feedback.
It's due to Material Theme UI see #7 . 
I've fixed this already will try to release the new version on weekend

**Comment by mskonovalov** [comment]
please check in new version
