### ISSUE TITLE
Problem w/ Material Theme UI`

### ISSUE THREAD

**Issue by vastsoun** [mskonovalov/intellij-hidpi-profiles#9]
Hi,

I use the HiDPI Profiles along with Material Theme UI plugin in both PyCharm and CLion. Recently, having upgraded both IDEs and the Material Theme UI plugin, switching between profiles does not work anymore.

My system:
Thinkpad P50
Ubuntu 16.04LTS
CLion 2017.3
PyCharm 2017.3

Details:
1. I think the issue is that the Material theme overrides the default theme settings in order to use the settings specific to the chose color scheme.
2. When switching between profiles, the Project pane and other fields do not change properly (spacing and font are messed up). However, just restarting the IDE after changing profiles fixes this specific issue. Its still annoying to have to restart all the time though.

**Comment by mskonovalov** [comment]
Hey @vastsoun, sad to hear you've faced the issue.
Are you sure you use the latest version of the plugin?
It is a common issue with this Material Theme and I've already fixed some.
Anyway I'll take a look asap and will try to fix the problem.

**Comment by vastsoun** [comment]
Hi again,

Yeah I just double checked and I am up-to-date on all plugins. I have also attached screenshots to demonstrate the problem. 

The first image shows how I have the "Mobile" profile setup for hi-res screen of the laptop only.
![screenshot from 2018-01-18 02-56-27](https://user-images.githubusercontent.com/2759676/35076997-5173d7dc-fbfb-11e7-9457-73a148dd91a5.png)

The second image shows the "Default" profile I use at work with the monitor. Notice how when I switch to this the spacing and display of the "Project" pane on the left gets messed-up.
![screenshot from 2018-01-18 02-56-34](https://user-images.githubusercontent.com/2759676/35076998-519e68f8-fbfb-11e7-92fd-1c06e12ce11f.png)

Now notice, after the restart of PyCharm, how the spacing goes back to normal.
![screenshot from 2018-01-18 03-01-02](https://user-images.githubusercontent.com/2759676/35077127-da8ecc16-fbfb-11e7-8239-3f3817234ea3.png)

I experience identical behavior on CLion.

**Comment by vastsoun** [comment]
Hi Mikhail,

Did you happen to have a look at the issue? I am not familiar with how the plugin works but I'm fairly seasoned in C/C++/Python, so I could pitch in and help. Just point me in the right direction.

**Comment by vastsoun** [comment]
Hi Mikhail,

Thanks for the fixes! When will the update become available to install automatically in CLion?

**Comment by mskonovalov** [comment]
Still waiting for JB moderation

**Comment by vastsoun** [comment]
Works great, thanks allot! :-D
